### ISSUE TITLE
Port pulses from HQCMeas

### ISSUE THREAD

**Issue by MatthieuDartiailh** [Ecpy/ecpy_pulses#1]
Doing this requires : 
- [x] getting rid of all occurrences of ContainerList by using a List and Signal (cf tasks in Ecpy)
- [x] update collection of sequences/shapes/context to use either declarators (like tasks) or simpler registration mechanism
- [x] update the testsuite
- [ ] redesign context/pre-compilation interaction to allow better use of advance capabilities of AWG (mean that the interaction with the driver need some thought too)

Only abstract tasks should be provided without concrete interfaces.

**Comment by PhilipVinc** [comment]
How can I ensure backwards compatibility for 

> dict.items()

In Python 3 it is equivalent to Python 2's dict.iteritems()

Right now the codebase is written using dict.iteritems(), and changing to dict.items() would break retrocompatibility. How can I avoid this?

**Comment by MatthieuDartiailh** [comment]
Use dict.items() it is a bit slower but is otherwise fine.

**Comment by MatthieuDartiailh** [comment]
Closed by #4
